### ISSUE TITLE
spam on affiliate program mailing list

### ISSUE THREAD

**Issue by gwenfranck** [cc-archive/internal#28]
I noticed an increased amount of spam making it to my inbox on the affiliate-programme mailing list (for example a daily notification from Cable Green on Linkedin, in Korean). Don't know if anything can be done about this.

**Comment by mattl** [comment]
Can you tell me where I can find this mailing list? It doesn't appear on our list of Ibiblio lists and it's not an internal group

**Comment by peterspdx** [comment]
No longer relevant; affiliate list is stagnant and will ultimately be closed out in light of new CCGN structure.
